version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  docker: circleci/docker@2.1.1
  gcp-cli: circleci/gcp-cli@1.3.0

jobs:
  pre-build-env:
    machine: true
    steps:
      - checkout
      - run:
          name: "Testing"
          command: |
            echo hello

workflows:
  Build and Push to GCR for Tag :
#     when:
#         matches:
#           pattern: "^$"
#           value: << pipeline.git.tag >>
    jobs:
      - pre-build-env
          
