version: 2.1
# orbs:
  # gcp-gcr: circleci/gcp-gcr@0.15.0

jobs:
  pre-build-env:
    machine: true
    steps:
      - checkout
  build-and-push-image:
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  Build and Push to GCR when using Tag:
    jobs:
      - pre-build-env:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build-and-push-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  Build and Push to GCR:
    jobs:
      - pre-build-env
      - build-and-push-image:
          filters:
            branches:
              only: main
