version: 2.1
jobs:
  build_server_pdfs:
    machine: true
    steps:
          - checkout
workflows:
  build-deploy:
    jobs:
      - build_server_pdfs: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            tags:
              only: /.*/
