version: 2.1
orbs:
  docker: circleci/docker@0.5.1

jobs:
  build_and_push_image:
    machine: true
    parameters:
      image:
        type: string
      tag:
        type: string
      extra_build_args:
        type: string

workflows:
  build-app:
    jobs:
      - build_and_push_image:
          context: standard-ci
          image: web-hosting
          cache_from: required-image
          tag: latest
          extra_build_args: "--build-arg BUILD_TYPE=dev"
          filters:
            branches:
              only: main
