version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/ShreyasSubhedar/sample-python-cfd/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_PASSWORD
jobs:
  my-first-job:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo Hello, World!
          mkdir target
          cd target
          touch demo.jar
      - persist_to_workspace:
          root: .
          paths:
            - target/demo.jar
#   my-second-job:
#     executor: my-custom-executor
#     steps:
#       - attach_workspace:
#           # Must be absolute path or relative path from working_directory
#           at: target/demo.jar

#       - run: |
#           ls -ltra
#           cd target
#           ls -ltra
      

workflows:
  my-custom-workflow:
    jobs:
      - my-first-job
      - gcp-gcr/build-and-push-image:
          context: standard-ci
          attach-workspace: true 
          use-docker-layer-caching: true
          google-project-id: GOOGLE_APP
          google-compute-zone: GOOGLE_COMPUTE_ZONE
          gcloud-service-key: GOOGLE_SERVICE_KEY
          image: adminui-v2
          requires:
            - my-first-job
#       - my-second-job:
#           requires:
#             - my-first-job
