version: 2.1
orbs:
  docker: circleci/docker@2.1.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          cache_from: python 
          use-buildkit: true 
          image: web-hosting 
          extra_build_args: --build-args TEST=dev 
          debug: true 
          lint-dockerfile: true 
          treat-warnings-as-errors: false 
          no_output_timeout: '15m' 

workflows:
  example-workflow:
    jobs:
      - example-job
