version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/ShreyasSubhedar/sample-python-cfd/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo Hello, World!
          mkdir target
          cd target
          touch demo.jar
      - persist_to_workspace:
          root: .
          paths:
            - target/demo.jar
          

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name