workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+(-pre\.\d+)?$/
            branches:
              ignore: /.*/
